---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "dr-development-messaging-secrets"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "dr-development-messaging"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  RABBITMQ_DEFAULT_PASS: "{{ .Values.secrets.dr_development_messaging.rabbitmq_password }}"
type: "Opaque"
