---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "identity-service"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "identity"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "identity"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "identity-http"
      protocol: "TCP"
      port: 61002
      targetPort: 61002
    - name: "identity-https"
      protocol: "TCP"
      port: 61001
      targetPort: 61001
