---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "tenantapplication-secrets"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "tenantapplication"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  ConnectionStrings__dr-development-db: "Host=dr-development-db-service;Port=5432;Username={{ .Values.config.tenantapplication.postgres_username }};Password={{ .Values.secrets.tenantapplication.postgres_password }}"
  DR_DEVELOPMENT_DB_PASSWORD: "{{ .Values.secrets.tenantapplication.postgres_password }}"
  DR_DEVELOPMENT_DB_URI: "postgresql://{{ .Values.config.tenantapplication.postgres_username }}:{{ .Values.secrets.tenantapplication.postgres_password }}@dr-development-db-service:5432"
  ConnectionStrings__dr-development-cache: "dr-development-cache-service:6379,password={{ .Values.secrets.tenantapplication.dr_development_cache_password }}"
  DR_DEVELOPMENT_CACHE_PASSWORD: "{{ .Values.secrets.tenantapplication.dr_development_cache_password }}"
  DR_DEVELOPMENT_CACHE_URI: "redis://:{{ .Values.secrets.tenantapplication.dr_development_cache_password }}@dr-development-cache-service:6379"
  ConnectionStrings__dr-development-messaging: "amqp://{{ .Values.config.tenantapplication.rabbitmq_username }}:{{ .Values.secrets.tenantapplication.rabbitmq_password }}@dr-development-messaging-service:5672"
  DR_DEVELOPMENT_MESSAGING_PASSWORD: "{{ .Values.secrets.tenantapplication.rabbitmq_password }}"
  DR_DEVELOPMENT_MESSAGING_URI: "amqp://{{ .Values.config.tenantapplication.rabbitmq_username }}:{{ .Values.secrets.tenantapplication.rabbitmq_password }}@dr-development-messaging-service:5672"
type: "Opaque"
