---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "tenantapplication-service"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "tenantapplication"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "tenantapplication"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "tenantapp-http"
      protocol: "TCP"
      port: 61032
      targetPort: 61032
    - name: "tenantapp-https"
      protocol: "TCP"
      port: 61031
      targetPort: 61031
