---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "dr-development-db-secrets"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "dr-development-db"
    app.kubernetes.io/instance: "{{.Release.Name}}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.dr_development_db.postgres_password }}"
type: "Opaque"
