---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "gateway-config"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.gateway.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.gateway.HTTP_PORTS }}"
  DATARIZEN_ASPIRE_RUN_ID: "{{ .Values.config.gateway.DATARIZEN_ASPIRE_RUN_ID }}"
  ReverseProxy__Clusters__tenantapplication__Destinations__destination1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__tenantapplication__Destinations__destination1__Address }}"
