---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "tenant-config"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "tenant"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.tenant.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.tenant.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.tenant.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.tenant.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.tenant.HTTP_PORTS }}"
  HTTPS_PORTS: "{{ .Values.config.tenant.HTTPS_PORTS }}"
  ASPNETCORE_URLS: "{{ .Values.config.tenant.ASPNETCORE_URLS }}"
  DATARIZEN_ASPIRE_RUN_ID: "{{ .Values.config.tenant.DATARIZEN_ASPIRE_RUN_ID }}"
  DR_DEVELOPMENT_DB_HOST: "{{ .Values.config.tenant.DR_DEVELOPMENT_DB_HOST }}"
  DR_DEVELOPMENT_DB_PORT: "{{ .Values.config.tenant.DR_DEVELOPMENT_DB_PORT }}"
  DR_DEVELOPMENT_DB_USERNAME: "{{ .Values.config.tenant.DR_DEVELOPMENT_DB_USERNAME }}"
  DR_DEVELOPMENT_DB_JDBCCONNECTIONSTRING: "{{ .Values.config.tenant.DR_DEVELOPMENT_DB_JDBCCONNECTIONSTRING }}"
  DR_DEVELOPMENT_CACHE_HOST: "{{ .Values.config.tenant.DR_DEVELOPMENT_CACHE_HOST }}"
  DR_DEVELOPMENT_CACHE_PORT: "{{ .Values.config.tenant.DR_DEVELOPMENT_CACHE_PORT }}"
  DR_DEVELOPMENT_MESSAGING_HOST: "{{ .Values.config.tenant.DR_DEVELOPMENT_MESSAGING_HOST }}"
  DR_DEVELOPMENT_MESSAGING_PORT: "{{ .Values.config.tenant.DR_DEVELOPMENT_MESSAGING_PORT }}"
  DR_DEVELOPMENT_MESSAGING_USERNAME: "{{ .Values.config.tenant.DR_DEVELOPMENT_MESSAGING_USERNAME }}"
  IDENTITY_HTTP: "{{ .Values.config.tenant.IDENTITY_HTTP }}"
  services__identity__http__0: "{{ .Values.config.tenant.services__identity__http__0 }}"
  IDENTITY_HTTPS: "{{ .Values.config.tenant.IDENTITY_HTTPS }}"
  services__identity__https__0: "{{ .Values.config.tenant.services__identity__https__0 }}"
  IDENTITY_IDENTITYHTTP: "{{ .Values.config.tenant.IDENTITY_IDENTITYHTTP }}"
  services__identity__identityHttp__0: "{{ .Values.config.tenant.services__identity__identityHttp__0 }}"
  IDENTITY_IDENTITYHTTPS: "{{ .Values.config.tenant.IDENTITY_IDENTITYHTTPS }}"
  services__identity__identityHttps__0: "{{ .Values.config.tenant.services__identity__identityHttps__0 }}"
