---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "tenant-service"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "tenant"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "tenant"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "http"
      protocol: "TCP"
      port: "{{ .Values.parameters.tenant.port_http }}"
      targetPort: "{{ .Values.parameters.tenant.port_http }}"
    - name: "https"
      protocol: "TCP"
      port: "{{ .Values.parameters.tenant.port_https }}"
      targetPort: "{{ .Values.parameters.tenant.port_https }}"
    - name: "tenantHttp"
      protocol: "TCP"
      port: 61012
      targetPort: 61012
    - name: "tenantHttps"
      protocol: "TCP"
      port: 61011
      targetPort: 61011
