---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "tenantapplication-config"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "tenantapplication"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "{{ .Values.config.tenantapplication.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "{{ .Values.config.tenantapplication.OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES }}"
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.tenantapplication.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.tenantapplication.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.tenantapplication.HTTP_PORTS }}"
  HTTPS_PORTS: "{{ .Values.config.tenantapplication.HTTPS_PORTS }}"
  DATARIZEN_ASPIRE_RUN_ID: "{{ .Values.config.tenantapplication.DATARIZEN_ASPIRE_RUN_ID }}"
  DR_DEVELOPMENT_DB_HOST: "{{ .Values.config.tenantapplication.DR_DEVELOPMENT_DB_HOST }}"
  DR_DEVELOPMENT_DB_PORT: "{{ .Values.config.tenantapplication.DR_DEVELOPMENT_DB_PORT }}"
  DR_DEVELOPMENT_DB_USERNAME: "{{ .Values.config.tenantapplication.DR_DEVELOPMENT_DB_USERNAME }}"
  DR_DEVELOPMENT_DB_JDBCCONNECTIONSTRING: "{{ .Values.config.tenantapplication.DR_DEVELOPMENT_DB_JDBCCONNECTIONSTRING }}"
  DR_DEVELOPMENT_CACHE_HOST: "{{ .Values.config.tenantapplication.DR_DEVELOPMENT_CACHE_HOST }}"
  DR_DEVELOPMENT_CACHE_PORT: "{{ .Values.config.tenantapplication.DR_DEVELOPMENT_CACHE_PORT }}"
  DR_DEVELOPMENT_MESSAGING_HOST: "{{ .Values.config.tenantapplication.DR_DEVELOPMENT_MESSAGING_HOST }}"
  DR_DEVELOPMENT_MESSAGING_PORT: "{{ .Values.config.tenantapplication.DR_DEVELOPMENT_MESSAGING_PORT }}"
  DR_DEVELOPMENT_MESSAGING_USERNAME: "{{ .Values.config.tenantapplication.DR_DEVELOPMENT_MESSAGING_USERNAME }}"
