---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tenantapplication-deployment"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "tenantapplication"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "datarizen"
        app.kubernetes.io/component: "tenantapplication"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "{{ .Values.parameters.tenantapplication.tenantapplication_image }}"
          name: "tenantapplication"
          envFrom:
            - configMapRef:
                name: "tenantapplication-config"
            - secretRef:
                name: "tenantapplication-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.tenantapplication.port_http }}"
            - name: "https"
              protocol: "TCP"
              containerPort: "{{ .Values.parameters.tenantapplication.port_https }}"
            - name: "tenantapplicationHttp"
              protocol: "TCP"
              containerPort: 61032
            - name: "tenantapplicationHttps"
              protocol: "TCP"
              containerPort: 61031
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "datarizen"
      app.kubernetes.io/component: "tenantapplication"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
