---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "dr-development-messaging-statefulset"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "dr-development-messaging"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "datarizen"
        app.kubernetes.io/component: "dr-development-messaging"
        app.kubernetes.io/instance: "{{.Release.Name}}"
    spec:
      containers:
        - image: "docker.io/library/rabbitmq:4.0-management-alpine"
          name: "dr-development-messaging"
          envFrom:
            - configMapRef:
                name: "dr-development-messaging-config"
            - secretRef:
                name: "dr-development-messaging-secrets"
          ports:
            - name: "tcp"
              protocol: "TCP"
              containerPort: 5672
            - name: "management"
              protocol: "TCP"
              containerPort: 15672
          volumeMounts:
            - name: "dr-development-messaging"
              mountPath: "/var/lib/rabbitmq"
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: "dr-development-messaging"
          emptyDir: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: "datarizen"
      app.kubernetes.io/component: "dr-development-messaging"
      app.kubernetes.io/instance: "{{.Release.Name}}"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    type: "RollingUpdate"
