parameters:
  identity:
    port_http: "8080"
    port_https: "8080"
    identity_image: "identity:latest"
  tenant:
    port_http: "8080"
    port_https: "8080"
    tenant_image: "tenant:latest"
  appbuilder:
    port_http: "8080"
    port_https: "8080"
    appbuilder_image: "appbuilder:latest"
  tenantapplication:
    port_http: "8080"
    port_https: "8080"
    tenantapplication_image: "tenantapplication:latest"
  gateway:
    port_http: "8080"
    port_https: "8080"
    gateway_image: "gateway:latest"
secrets:
  dr_development_db:
    POSTGRES_PASSWORD: "datarizen!"
    postgres_password: "datarizen!"
  dr_development_cache:
    REDIS_PASSWORD: ""
  dr_development_messaging:
    RABBITMQ_DEFAULT_PASS: ""
  identity:
    postgres_password: "datarizen!"
    dr_development_cache_password: ""
    rabbitmq_password: ""
  tenant:
    postgres_password: "datarizen!"
    dr_development_cache_password: ""
    rabbitmq_password: ""
  appbuilder:
    postgres_password: "datarizen!"
    dr_development_cache_password: ""
    rabbitmq_password: ""
  tenantapplication:
    postgres_password: "datarizen!"
    dr_development_cache_password: ""
    rabbitmq_password: ""
config:
  dr_development_db:
    POSTGRES_USER: "datarizen"
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
  dr_development_messaging:
    RABBITMQ_DEFAULT_USER: "admin"
  dr_development_dbadmin:
    PGADMIN_DEFAULT_EMAIL: "admin@datarizen.com"
    PGADMIN_DEFAULT_PASSWORD: "dr-development"
    PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    PGADMIN_REPLACE_SERVERS_ON_STARTUP: "True"
    DATARIZEN_PG_HOST: "dr-development-db"
  identity:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTPS_PORTS: "61001"
    DATARIZEN_ASPIRE_RUN_ID: "20260219140544-7c6c020df6164540bb6d47da8bd67fb0"
    DR_DEVELOPMENT_DB_HOST: "dr-development-db-service"
    DR_DEVELOPMENT_DB_PORT: "5432"
    DR_DEVELOPMENT_DB_USERNAME: "datarizen"
    DR_DEVELOPMENT_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://dr-development-db-service:5432"
    DR_DEVELOPMENT_CACHE_HOST: "dr-development-cache-service"
    DR_DEVELOPMENT_CACHE_PORT: "6379"
    DR_DEVELOPMENT_MESSAGING_HOST: "dr-development-messaging-service"
    DR_DEVELOPMENT_MESSAGING_PORT: "5672"
    DR_DEVELOPMENT_MESSAGING_USERNAME: "admin"
    postgres_username: "datarizen"
    rabbitmq_username: "admin"
  tenant:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: "61012"
    HTTPS_PORTS: "61011"
    ASPNETCORE_URLS: "http://+:61012"
    DATARIZEN_ASPIRE_RUN_ID: "20260219140544-7c6c020df6164540bb6d47da8bd67fb0"
    DR_DEVELOPMENT_DB_HOST: "dr-development-db-service"
    DR_DEVELOPMENT_DB_PORT: "5432"
    DR_DEVELOPMENT_DB_USERNAME: "datarizen"
    DR_DEVELOPMENT_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://dr-development-db-service:5432"
    DR_DEVELOPMENT_CACHE_HOST: "dr-development-cache-service"
    DR_DEVELOPMENT_CACHE_PORT: "6379"
    DR_DEVELOPMENT_MESSAGING_HOST: "dr-development-messaging-service"
    DR_DEVELOPMENT_MESSAGING_PORT: "5672"
    DR_DEVELOPMENT_MESSAGING_USERNAME: "admin"
    IDENTITY_IDENTITYHTTP: "http://identity-service:61002"
    services__identity__identityHttp__0: "http://identity-service:61002"
    IDENTITY_IDENTITYHTTPS: "https://identity-service:61001"
    services__identity__identityHttps__0: "https://identity-service:61001"
    postgres_username: "datarizen"
    rabbitmq_username: "admin"
  appbuilder:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTPS_PORTS: "61021"
    DATARIZEN_ASPIRE_RUN_ID: "20260219140544-7c6c020df6164540bb6d47da8bd67fb0"
    DR_DEVELOPMENT_DB_HOST: "dr-development-db-service"
    DR_DEVELOPMENT_DB_PORT: "5432"
    DR_DEVELOPMENT_DB_USERNAME: "datarizen"
    DR_DEVELOPMENT_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://dr-development-db-service:5432"
    DR_DEVELOPMENT_CACHE_HOST: "dr-development-cache-service"
    DR_DEVELOPMENT_CACHE_PORT: "6379"
    DR_DEVELOPMENT_MESSAGING_HOST: "dr-development-messaging-service"
    DR_DEVELOPMENT_MESSAGING_PORT: "5672"
    DR_DEVELOPMENT_MESSAGING_USERNAME: "admin"
    postgres_username: "datarizen"
    rabbitmq_username: "admin"
  tenantapplication:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTPS_PORTS: "61031"
    DATARIZEN_ASPIRE_RUN_ID: "20260219140544-7c6c020df6164540bb6d47da8bd67fb0"
    DR_DEVELOPMENT_DB_HOST: "dr-development-db-service"
    DR_DEVELOPMENT_DB_PORT: "5432"
    DR_DEVELOPMENT_DB_USERNAME: "datarizen"
    DR_DEVELOPMENT_DB_JDBCCONNECTIONSTRING: "jdbc:postgresql://dr-development-db-service:5432"
    DR_DEVELOPMENT_CACHE_HOST: "dr-development-cache-service"
    DR_DEVELOPMENT_CACHE_PORT: "6379"
    DR_DEVELOPMENT_MESSAGING_HOST: "dr-development-messaging-service"
    DR_DEVELOPMENT_MESSAGING_PORT: "5672"
    DR_DEVELOPMENT_MESSAGING_USERNAME: "admin"
    postgres_username: "datarizen"
    rabbitmq_username: "admin"
  gateway:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES: "true"
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    DATARIZEN_ASPIRE_RUN_ID: "20260219140544-7c6c020df6164540bb6d47da8bd67fb0"
    ReverseProxy__Clusters__controlpanel__Destinations__destination1__Address: "http://tenant-service:61012"
    ReverseProxy__Clusters__appbuilder__Destinations__destination1__Address: "http://appbuilder-service:61022"
    ReverseProxy__Clusters__tenantapplication__Destinations__destination1__Address: "http://tenantapplication-service:61032"
