---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "appbuilder-service"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "appbuilder"
    app.kubernetes.io/instance: "{{.Release.Name}}"
spec:
  type: "ClusterIP"
  selector:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "appbuilder"
    app.kubernetes.io/instance: "{{.Release.Name}}"
  ports:
    - name: "appbldr-http"
      protocol: "TCP"
      port: 61022
      targetPort: 61022
    - name: "appbldr-https"
      protocol: "TCP"
      port: 61021
      targetPort: 61021
