---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "dr-development-db-config"
  labels:
    app.kubernetes.io/name: "datarizen"
    app.kubernetes.io/component: "dr-development-db"
    app.kubernetes.io/instance: "{{.Release.Name}}"
data:
  POSTGRES_HOST_AUTH_METHOD: "{{ .Values.config.dr_development_db.POSTGRES_HOST_AUTH_METHOD }}"
  POSTGRES_INITDB_ARGS: "{{ .Values.config.dr_development_db.POSTGRES_INITDB_ARGS }}"
  POSTGRES_USER: "{{ .Values.config.dr_development_db.POSTGRES_USER }}"
